import streamlit as st

from utils.helper import page_header, footer


# ============================================================
# SOIL ANALYSIS
# ============================================================

def analyze_soil(
    nitrogen,
    phosphorus,
    potassium,
    ph,
    moisture,
):
    """
    Calculate a simple soil-health score based on the
    parameter ranges used by the original AgriOne AI page.
    """

    score = 0
    recommendations = []

    # Nitrogen
    if 80 <= nitrogen <= 140:
        score += 20
    else:
        recommendations.append(
            "Adjust Nitrogen level based on a soil test."
        )

    # Phosphorus
    if 40 <= phosphorus <= 80:
        score += 20
    else:
        recommendations.append(
            "Adjust Phosphorus level based on a soil test."
        )

    # Potassium
    if 40 <= potassium <= 80:
        score += 20
    else:
        recommendations.append(
            "Adjust Potassium level based on a soil test."
        )

    # pH
    if 6.0 <= ph <= 7.5:
        score += 20
    else:
        recommendations.append(
            "Maintain soil pH between 6.0 and 7.5 "
            "according to crop requirements."
        )

    # Moisture
    if 40 <= moisture <= 70:
        score += 20
    else:
        recommendations.append(
            "Improve irrigation management and monitor soil moisture."
        )

    # Health category
    if score >= 90:
        health = "Excellent"
    elif score >= 70:
        health = "Good"
    elif score >= 50:
        health = "Average"
    else:
        health = "Poor"

    return health, score, recommendations


# ============================================================
# CROP SUGGESTIONS
# ============================================================

def get_suitable_crops(ph, moisture):
    """
    Provide simple crop suggestions based on pH and moisture.
    """

    if 6.0 <= ph <= 7.5:

        if moisture >= 60:
            return [
                "🌾 Rice",
                "🌽 Maize",
                "🥔 Potato",
            ]

        return [
            "🌱 Groundnut",
            "🌻 Sunflower",
            "🌿 Cotton",
        ]

    return [
        "🌾 Millets",
        "🌱 Pulses",
    ]


# ============================================================
# REPORT GENERATOR
# ============================================================

def create_soil_report(
    nitrogen,
    phosphorus,
    potassium,
    ph,
    moisture,
    health,
    score,
    crops,
    recommendations,
):
    recommendations_text = (
        "\n".join(
            f"- {item}"
            for item in recommendations
        )
        if recommendations
        else "- No major recommendations."
    )

    crops_text = (
        "\n".join(
            f"- {crop}"
            for crop in crops
        )
        if crops
        else "- No crop suggestions available."
    )

    return f"""
========================================
             AGRIONE AI
           SOIL REPORT
========================================

Soil Parameters
----------------------------------------

Nitrogen (N)   : {nitrogen}
Phosphorus (P) : {phosphorus}
Potassium (K)  : {potassium}
Soil pH        : {ph}
Moisture       : {moisture} %

----------------------------------------
Soil Health
----------------------------------------

Health         : {health}
Health Score   : {score}/100

----------------------------------------
Suitable Crops
----------------------------------------

{crops_text}

----------------------------------------
Recommendations
----------------------------------------

{recommendations_text}

========================================
Generated by AgriOne AI
========================================
"""


# ============================================================
# PAGE
# ============================================================

def app():

    page_header("🌱 Soil Analysis")

    st.write(
        "Enter soil parameters to evaluate soil health "
        "and receive simple recommendations."
    )

    st.info(
        "For accurate fertilizer and soil-treatment decisions, "
        "use a professional soil test report."
    )

    st.divider()

    # --------------------------------------------------------
    # Inputs
    # --------------------------------------------------------

    col1, col2 = st.columns(2)

    with col1:

        nitrogen = st.number_input(
            "Nitrogen (N)",
            min_value=0.0,
            max_value=300.0,
            value=90.0,
            step=1.0,
            key="soil_nitrogen",
        )

        phosphorus = st.number_input(
            "Phosphorus (P)",
            min_value=0.0,
            max_value=300.0,
            value=50.0,
            step=1.0,
            key="soil_phosphorus",
        )

        potassium = st.number_input(
            "Potassium (K)",
            min_value=0.0,
            max_value=300.0,
            value=50.0,
            step=1.0,
            key="soil_potassium",
        )

    with col2:

        ph = st.number_input(
            "Soil pH",
            min_value=0.0,
            max_value=14.0,
            value=6.5,
            step=0.1,
            key="soil_ph",
        )

        moisture = st.slider(
            "Soil Moisture (%)",
            min_value=0,
            max_value=100,
            value=60,
            step=1,
            key="soil_moisture",
        )

    st.divider()

    # --------------------------------------------------------
    # Analyze
    # --------------------------------------------------------

    if st.button(
        "🔍 Analyze Soil",
        type="primary",
        use_container_width=True,
    ):

        health, score, recommendations = analyze_soil(
            nitrogen,
            phosphorus,
            potassium,
            ph,
            moisture,
        )

        crops = get_suitable_crops(
            ph,
            moisture,
        )

        # Save result in session state so it doesn't disappear
        # during normal Streamlit reruns.
        st.session_state["soil_result"] = {
            "nitrogen": nitrogen,
            "phosphorus": phosphorus,
            "potassium": potassium,
            "ph": ph,
            "moisture": moisture,
            "health": health,
            "score": score,
            "recommendations": recommendations,
            "crops": crops,
        }

    # --------------------------------------------------------
    # Display Result
    # --------------------------------------------------------

    result = st.session_state.get(
        "soil_result"
    )

    if result is None:

        st.info(
            "Enter the soil values above and click "
            "Analyze Soil."
        )

        st.markdown("---")

        st.info(
            "🌱 Healthy soil is the foundation "
            "of a productive farm."
        )

        footer()

        return

    # --------------------------------------------------------
    # Health Result
    # --------------------------------------------------------

    st.subheader(
        "📊 Soil Health Result"
    )

    result_col1, result_col2 = st.columns(2)

    with result_col1:

        st.metric(
            "Soil Health",
            result["health"],
        )

    with result_col2:

        st.metric(
            "Health Score",
            f'{result["score"]}/100',
        )

    st.progress(
        result["score"] / 100
    )

    # --------------------------------------------------------
    # Status Message
    # --------------------------------------------------------

    if result["score"] >= 90:

        st.success(
            "Excellent soil condition according to this screening."
        )

    elif result["score"] >= 70:

        st.success(
            "Good soil condition. Continue monitoring regularly."
        )

    elif result["score"] >= 50:

        st.warning(
            "Average soil condition. Consider improving "
            "the parameters listed below."
        )

    else:

        st.error(
            "Poor soil condition. Consider obtaining "
            "a professional soil test."
        )

    # --------------------------------------------------------
    # Parameters
    # --------------------------------------------------------

    st.subheader(
        "🧪 Soil Parameters"
    )

    p1, p2, p3 = st.columns(3)

    with p1:

        st.metric(
            "Nitrogen",
            f'{result["nitrogen"]:.1f}',
        )

    with p2:

        st.metric(
            "Phosphorus",
            f'{result["phosphorus"]:.1f}',
        )

    with p3:

        st.metric(
            "Potassium",
            f'{result["potassium"]:.1f}',
        )

    p4, p5 = st.columns(2)

    with p4:

        st.metric(
            "pH",
            f'{result["ph"]:.1f}',
        )

    with p5:

        st.metric(
            "Moisture",
            f'{result["moisture"]}%',
        )

    # --------------------------------------------------------
    # Suitable Crops
    # --------------------------------------------------------

    st.subheader(
        "🌾 Suitable Crops"
    )

    crop_columns = st.columns(
        len(result["crops"])
    )

    for column, crop in zip(
        crop_columns,
        result["crops"],
    ):

        with column:

            st.success(
                crop
            )

    # --------------------------------------------------------
    # Recommendations
    # --------------------------------------------------------

    st.subheader(
        "💡 Recommendations"
    )

    if result["recommendations"]:

        for recommendation in result[
            "recommendations"
        ]:

            st.warning(
                recommendation
            )

    else:

        st.success(
            "✅ All evaluated soil parameters are within "
            "the target ranges."
        )

    # --------------------------------------------------------
    # Download Report
    # --------------------------------------------------------

    st.subheader(
        "📄 Download Soil Report"
    )

    report = create_soil_report(
        result["nitrogen"],
        result["phosphorus"],
        result["potassium"],
        result["ph"],
        result["moisture"],
        result["health"],
        result["score"],
        result["crops"],
        result["recommendations"],
    )

    st.download_button(
        label="📥 Download Report",
        data=report,
        file_name="AgriOne_AI_Soil_Report.txt",
        mime="text/plain",
        use_container_width=True,
    )

    # --------------------------------------------------------
    # Reset
    # --------------------------------------------------------

    if st.button(
        "🗑️ Clear Soil Analysis",
        use_container_width=True,
    ):

        st.session_state.pop(
            "soil_result",
            None,
        )

        st.rerun()

    # --------------------------------------------------------
    # Footer
    # --------------------------------------------------------

    st.markdown("---")

    st.info(
        "🌱 Healthy soil is the foundation "
        "of a productive farm."
    )

    footer()